 

development:
  adapter: postgresql
  database: my_database_development
  username: postgres
  password: prakash24	
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  username: postgres
  password: prakash24
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  username: postgres
  password: prakash24
  pool: 5
  timeout: 5000